FROM rethink/testbed-baseline

MAINTAINER marc.emmelmann@fokus.fraunhofer.de

RUN mkdir /opt/reTHINK/catalogue

CMD echo "Baseline installation for reTHINK Catalogue; All code is under /opt/reTHINK"

